---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: datahub-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: datahub-tap
spec:
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: BP_WEB_SERVER
      value: nginx
  source:
    git:
      url: https://github.com/agapebondservant/datahub-accelerator.git
      ref:
        branch: main